Домашнее задание к лекции "Функции"
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

перечень всех документов
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
Общие требования к программе:

код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
в коде отсутствуют глобальные переменные (за исключением documents и directories);
пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды "q").

In [169]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

In [7]:
def path_doc(directories, n='empty'):
    if n == 'empty':
        n = input("Введите номер документа")
        
    for key, value in directories.items():
        for i in value:
            if i == n: 
                #print(key)
                return [f'Документ хранится на полке: {key}', key]
    return f'Документ не найден в базе' 

#path_doc(directories, n='empty')[1]

In [8]:
def owner_doc(directories):
    n = input("Введите номер документа")
    s = [i["name"]  for i in documents if i["number"] == n] 
    if len(s) != 0:
        return f'Владелец документа: {"".join(s)}'
    else:
        return "Документ не найден в базе"
    #return f'Владелец документа: {"".join(s)}' if len(s) != 0 else return "Документ не найден в базе"

owner_doc (directories) 

Введите номер документа1


'Документ не найден в базе'

In [190]:
def all_info_about_docs (documents, directories):
    s = []
    for i in documents:
        s.append(f'№: {i["number"]}, ' \
                f'тип: {i["type"]}, ' \
                f'владелец: {i["name"]}, ' \
                f'полка хранения: {path_doc(directories, i["number"])[1]}')
    return s      
all_info_about_docs (documents,directories)
#documents 

['№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1',
 '№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1',
 '№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2']

In [18]:
def count_ds (directories):
    return (f'Текущий перечень полок: {", ".join(list(directories.keys()))}')

In [11]:
def add_ds (directories):
    t = input("Введите номер полки")
    if t in directories:
        print( f'Такая полка уже существует.'
              f' {count_ds (directories)}')
    else:
        directories[t] = []
        print(f'Полка добавлена.'
              f' {count_ds (directories)}')
        
add_ds (directories)




Введите номер полки1
Такая полка уже существует. Текущий перечень полок: 1, 2, 3


In [12]:
def delete_ds (directories):
    t = input("Введите номер полки")
    if t in directories:
        if len(directories[t]) == 0:
            del directories[t]
            return f'Полка удалена. {count_ds(directories)}'
        else:
            return f'На полке есть документ, удалите их перед удалением полки. {count_ds(directories)}'
    else:
        return f'Такой полки не существует. {count_ds(directories)}'
            
delete_ds (directories)

Введите номер полки1


'На полке есть документ, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3'

In [160]:
def add_doc(documents, directories):
    n_doc = input("Введите номер документа:")
    type_doc = input("Введите тип документа:")
    owner_doc = input("Введите владельца документа:")
    ds_doc = input("Введите полку для хранения:")
    
    if ds_doc in directories:
        documents.append({'type': type_doc, 'number': n_doc, 'name': owner_doc})
        print('Документ добавлен. Текущий список документов:')
        return all_info_about_docs (documents, directories)
    else: 
        return f'Такой полки не существует. Добавьте полку командой as.'

add_doc(documents, directories)
#print (documents)

Введите номер документа:1
Введите тип документа:1
Введите владельца документа:1
Введите полку для хранения:1
Документ добавлен. Текущий список документов:


['№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1',
 '№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1',
 '№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2',
 '№: 1, тип: 1, владелец: 1, полка хранения: о']

Пункт 2. Пользователь по команде "d" может удалить документ из данных
Примеры работы:

Введите команду:
d

Введите номер документа:
10006
Результат:

Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
Введите команду:
d

Введите номер документа:
123456
Результат:

Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [189]:
def del_doc(documents, directories):
    n_doc = input("Введите номер документа:")
    for i in documents:
        if i["number"] == n_doc:
            #documents.remove(i)
            for value in directories.values():
                #if value == n_doc:
                    value.remove(n_doc)
            print('Документ удалён. Текущий список документов:')
            #return all_info_about_docs (documents, directories)
    
    
del_doc(documents, directories)
print (directories)

Введите номер документа:1
{'1': ['2207 876234', '11-2'], '2': ['10006'], '3': []}


In [ ]:
def main(documents, directories):
    while True:
        t = input("Введите команду")
        if t == 'p':
            print(owner_doc(documents)) 
        elif t == 's':
            print(path_doc(directories)[0])
        elif t == 'l':
            print(*all_info_about_docs(documents, directories), sep ='\n')
        elif t == 'ads':
            add_ds (directories)
        elif t == 'ds':
            print(delete_ds (directories))
        elif t == 'ad':
            print(*add_doc (documents, directories), sep ='\n')
        #elif t == 'd':
            #print(*del_doc (documents, directories), sep ='\n')
        elif t == 'q': break 
    
main(documents, directories)
